#Umbrellaz configuration
#Mon Sep 28 14:01:28 GMT-03:00 2026
restricted_spawn.pitch=0.0
restricted_spawn.world=minecraft\:overworld
restricted_spawn.x=0.0
restricted_spawn.y=80.0
restricted_spawn.yaw=0.0
restricted_spawn.z=0.0
